"""empty message

Revision ID: 1d2551dac447
Revises: 75ed607a6e28
Create Date: 2024-07-26 10:55:54.309992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d2551dac447'
down_revision = '75ed607a6e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_article', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('ix_t_article_username')

    op.drop_table('t_article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_article',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=120), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_article', schema=None) as batch_op:
        batch_op.create_index('ix_t_article_username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
