"""empty message

Revision ID: 75ed607a6e28
Revises: 
Create Date: 2024-07-26 10:48:54.305120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ed607a6e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('t_article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_article_username'), ['username'], unique=True)

    op.create_table('t_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_t_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_user_username'))

    op.drop_table('t_user')
    with op.batch_alter_table('t_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_t_article_username'))

    op.drop_table('t_article')
    # ### end Alembic commands ###
